version: '3.8'

services:
  # This is the name of our service
  calculator-server:
    # Tell Compose to build the image from the current directory using our Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Give the built image a friendly name for easier management
    image: mcp/calculator-stdio-server:latest

    # --- CRITICAL FOR STDIO SERVERS ---
    # These two lines are the equivalent of 'docker run -it'.
    # They are essential for your MCP client to connect to the server's
    # standard input and output streams.
    stdin_open: true # Keeps stdin open (-i)
    tty: true # Allocates a pseudo-TTY (-t)

    # Give the running container a predictable name
    container_name: mcp_calculator_server

    # Optional: Automatically restart the container if it crashes
    restart: unless-stopped

    # Environment variables (if needed for MCP SDK)
    environment:
      - NODE_ENV=production
      - MCP_TRANSPORT=stdio

    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
